language: python
python:
- '2.7'
- '3.6'
install: pip install .
script: ./runtests.sh
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: scales-rpc-upload
  password:
    secure: aERkZtNk4EdOUKhWJr30yRRzNliqQwdsZjPCi/M8xzuqQk9CnscbLQfqlO4Yu5HAbnvD9ezMdJCprm+bw4+ISADkMcD6DzMtdO61ND6LrIpm5SsZ57Vmwif1BAv8GpDaBUkwkom7OuEZTkoo/snXwehnLnjD6Vo9WzBt5AXGW3D6Y384hhd/sHQ+ZGiruj7w3qX7/h4RuIIFOp1G0n8PTMg2Sz7mNrMdiNSQu8ipPPPJcVz1AGFqwnxvs+fDSKpCNNp488HWZEuRsiggBP+adWDKPIMsarnCkAf+xciGOG27ngklQwu7n5wTv1+1hpt/KgNV3ob/T3WUkFQYU6xx0n12aWWANBFQj83noJeRkYyKwN0cwr40tjoiXFzXLraYhypOu2d8CXBldcCpro35GJpfQTDUolG3ozpgxcTgqmgB38NArCXvsZqtVAXydXDnyzgFwWwN1JvH6h8SwRwzV8PjPLIsPIdQWl6icrzYBDgriveJPrvR3PMffzsL87RF+iXxQRNKv/2IYJnB5jrFbTeUyppkY0Jp0kzkxNWMBUX+H1juSKXCa3uLViRy0CmxgKFSfdtIr4X83ed1nDMbiq7bKI4M52q+zBYtpUbUzVnjv3Iq5eJqXYu6qqONsTjC5yprsgqcWvHwtFyKzejHuPEVJ1OU3x4v8bHx5qdz0Ho=
  on:
    tags: true
